# Objetivo(s)

O objetivo principal do trabalho é entender o processo de acentuação no Português Brasileiro, com base em um experimento utilizando pseudopalavras. Ou seja, buscamos compreender quais as características da palavra e quais as características do falante que influenciam nesse processo de acentuação tônica quando o indivíduo se depara com uma palavra nova. 

Algumas perguntas a serem respondidas pela análise estatística são: 

1. A classificação tônica das pseudopalavras pode recuperar o acento das palavras-alvo
de referência? Em outras palavras, queremos entender se a tonicidade da palavra-alvo tem papel na predição do acento da pseudopalavra.
 
2. As características estruturais da pseudopalavra têm influência 
no processo de acentuação tônico? Essa é a única característica que realmente tem impacto nesse processo?

3. A similaridade entre palavra-alvo e pseudopalavra influencia na associação acentual? Buscamos entender se quanto mais similar a pseudopalavra for da palavra-alvo, maiores são as chances de atribuição do mesmo padrão acentual da palavra-alvo.

4. As variáveis selecionadas pelo modelo estão em concordância com a literatura 
da área?  Existem variáveis linguísticas, extralinguísticas -relacionadas aos participantes- e experimentais -relacionadas ao estudo-, que podem, segundo a literatura da área, influenciar o comportamento acentual no português. 

5. Há associação entre graduação em letras e a classificação tônica da pseudopalavra?
Há associação entre conhecimento em música e a classificação tônica da pseudopalavra? 
Espera-se que indivíduos com conhecimento em música ou que entraram recentemente em letras tenham um comportamento de classificação das pseudopalavras distinto dos demais.



