# Descrição do estudo {#descricao-estudo}

O experimento consistia em apresentar aos participantes, através do software
Psychopy, uma série de pseudopalavras e registrar, via Google Meet, a forma 
como eles reproduziam verbalmente tais palavras. A seguir, as respostas dos
participantes foram classificadas de acordo com as três classes de acentuação
tônica: oxítona, paroxítona e proparoxítona. Essa é a variável dependente do
estudo, que será descrita junto às outras variáveis no capítulo
\@ref(variaveis).

A coleta dos dados foi realizada no início do primeiro semestre de 2020 com 34
indivíduos que, através de divulgações em redes sociais e de colegas, se
voluntariaram a participar do experimento. Os pré-requisitos eram de que tais
voluntários não tivessem estudado linguística, fossem maior de 18 anos e 
falantes nativos do português brasileiro. 

Na amostra encontram-se estudantes do primeiro semestre da faculdade de Letras 
da Universidade de São Paulo, músicos, alguns residentes de fora do estado de 
São Paulo, entre outros. Supõe-se que os alunos do primeiro semestre do curso de
Letras ainda não têm conhecimento na área. O perfil dos participantes é descrito
nas tabelas e gráficos na seção \@ref(descritiva). 

## Problemas na coleta dos dados

Identificamos duas potenciais falhas na coleta dos dados:

1. Problemas técnicos e interferência externa;
1. Problemas de aleatorização.

__Problemas técnicos e interferência externa__: 

Destaca-se a perda de algumas respostas durante o processo de coleta de dados,
visto que ruídos externos impediram que algumas entonações fossem captadas e 
registradas na gravação. Logo, na base de dados não temos 372 registros para 
todos os participantes. Portanto, um total de 12.511 dados serão utilizados na
análise.

__Problemas de aleatorização__:

Inicialmente, as pseudopalavras foram aleatorizadas de forma geral no software
_Excel_ (ALEATORIo ENTRE) e separadas em 4 blocos com 93 pseudopalavras cada,
resultando em um total de 372 palavras criadas. Dentro de cada bloco, a ordem em
que as pseudopalavras foram apresentadas aos falantes também foi aleatorizada,
porém, para alguns participantes o software Psychopy apresentou problemas e eles
tiveram que continuar o experimento a partir de slides com uma ordem aleatória
pré-estabelecida.

Em outras palavras, todos os indivíduos que em algum momento acompanharam o
experimento pelos slides seguiram com palavras apresentadas na mesma ordem (a
primeira aleatorização retirada do Excel). 

As palavras que deram origem às pseudopalavras, definidas como palavras alvo, foram classificadas em dois níveis de acordo com a sua ocorrência no  _Corpus brasileiro_, corpus linguístico coordenado pelo pesquisador Antonio Paulo Berber Sardinha. Se a palavra possui mais de 100 mil ocorrências no corpus ela é classificada como alta frequência e se possui menos de 2 mil ocorrências ela é classificada como baixa frequência. Ademais, as pseudopalavras foram construídas com três sílabas de extensão para que os três padrões acentuais do português brasileiro pudessem ser produzidos. A junção da ideia de frequência e similaridade entre a palavra alvo e a pseudopalavra resultou na criação de uma variável com 4 categorias chamada grupo de estímulos (alta frequência + similaridade, alta frequência + dissimilaridade, baixa frequência + similaridade, baixa frequência + dissimilaridade). Ressaltamos que essa variável não foi controlada durante a coleta de dados, ou seja, não foi definido uma quantidade de palavras de cada categoria em cada bloco

Outro ponto importante está relacionado aos testes para validar se a pseudopalavra é similar a palavra a partir da qual ela foi criada (palavra alvo). Nessa etapa, pediu-se para 10 falantes do português, que não participaram do estudo, listarem a palavra real a qual eles associavam a palavra inventada. Considerou-se como validadas as pseudopalavras cuja associação foi a palavra alvo na resposta de, no mínimo, oito indivíduos. Pseudopalavras com um número de associações corretas menor que oito foram consideradas não validadas, porém, pseudopalavras nas quais sete falantes apresentaram a associação correta foram classificadas como quase validadas.  
  
Da mesma forma, foram consideradas validadas como dissimilares à palavra alvo pseudopalavras não associadas a uma mesma resposta por mais de dois indivíduos. Ressalta-se que a associação não necessariamente precisa ser com a palavra alvo. Pseudopalavras com um número de associações maior que dois foram consideradas não validadas,porém,pseudopalavras nas quais três falantes apresentaram a mesma associação foram classificadas como quase validadas

Por fim, destacamos que a variável relacionada aos falantes será considerada aleatória, pois são uma amostra da população dos falantes do português brasileiro e, além disso, porque cada participante apresentou mais de uma resposta no estudo

