# Descrição das variáveis {#descricao-variaveis}

Foram coletadas variáveis linguísticas -relacionadas às pseudopalavras-, 
extralinguísticas -relacionadas aos participantes- e experimentais -relacionadas 
ao estudo-, que podem, segundo a literatura da área, influenciar o comportamento
acentual no português. A seguir, listamos as variáveis pré-selecionadas para o estudo. 
  
  
## Variável Dependente

A variável resposta de interesse é __Tonicidade de produção__, ou seja, a
classificação acentual tônica da pseudopalavra (oxítona, paroxítona e proparoxítona).
  
  
## Variáveis Linguísticas

As pseudopalavras foram construídas com três sílabas de extensão para 
que os três padrões acentuais do português brasileiro pudessem ser produzidos.
As palavras que deram origem às pseudopalavras, definidas como palavras-alvo,
foram classificadas em dois níveis de acordo com a sua ocorrência no Corpus
brasileiro, corpus linguístico coordenado pelo pesquisador Antonio Paulo Berber
Sardinha. Se a palavra possui mais de 100 mil ocorrências no corpus ela é
classificada como de alta frequência e se possui menos de 2 mil ocorrências ela é
classificada como de baixa frequência. A junção da ideia de frequência e similaridade
entre a palavra alvo e a pseudopalavra resultou na criação de uma variável com 4
categorias chamada grupo de classificação. 

- __Validação__: s = sim, n = não validada e q = quase validada
- __Vizinhança tonicidade__: indica qual foi o padrão acentual das palavras que os participantes julgaram similares a pseudopalavras criada; apenas para pseudopalavras não validadas
- __Taxa de validação__: indica quantas pessoas do estudo preliminar informaram que
a palavra era similar ou dissimilar
- __Palavra alvo__: palavra real que deu origem à pseudopalavra  
- __Tonicidade da palavra alvo__: oxítona, paroxítona e proparoxítona
- __Estrutura da palavra__: indica qual é a estrutura da pseudopalavra (CV-CV-CV ou 
CV-CV-CVC), sendo que C indica Consoante e V indica Vogal
- __Pseudopalavra__: refere-se a cada uma das palavras criadas
- __Segmento modificado__: indica qual letra foi modificada na criação da pseudopalavra
a partir da palavra real (consoante ou vogal)  
- __Sílaba modificada__: 1,2,3 ( 1º,2º,3º) ou 0 quando mais de uma sílaba
 foi modificada (caso das palavras dissimilares)
- __Grupo de classificação__:  indica o efeito da similaridade (entre a pseudopalavra 
e a palavra real) e da frequência (alta e baixa) na produção acentual
     
  - 1 = pseudopalavras similares de alta frequência    
  - 2 = pseudopalavras dissimilares de alta frequência   
  - 3 = pseudopalavras similares de baixa frequência    
  - 4 = pseudopalavras dissimilares de baixa frequência   
  
Ressaltamos que essa variável não foi controlada durante a coleta
de dados, ou seja, não foi pré-definido uma quantidade de palavras de cada categoria
em cada conjunto apresentado aos participantes. 
    
- __Taxa de similaridade__: Para mudanças de consoante:1, 2, 3 (grupos similares), 5, 6, 7, 8, 9, 10 (grupos dissimilares); para mudanças de vogal :1 (grupos similares), 5, 6, 7, 8 (grupos dissimilares)


## Variáveis Extralinguísticas
  
- __Participante__: identifica os 34 participantes do experimento
- __Idade__: de 18 a 60 (anos)
- __Gênero__: feminino e masculino
- __Escolaridade__: categorizada em Fundamental Completo, Superior Completo, Superior Incompleto e Pós-Graduação (Completo ou Incompleta)
- __Área de formação__: 0 = outros e 1 = letras
- __Línguas__: 0 = não tem conhecimento em línguas e 1 = tem conhecimento em línguas
- __Música__: 0 = não tem conhecimento em música e 1 = tem conhecimento em música

## Variáveis Experimentais {#var-experimentais}

As palavras foram aleatorizadas no Excel e divididas em 4 conjuntos - variável Bloco
de apresentação- a serem apresentados aos participantes com um intervalo de tempo entre 
cada conjunto. Por limitações do software, a ordem de apresentação desses conjuntos 
não pôde ser aleatorizada, apenas a ordem das palavras dentro de cada conjunto.

- __Bloco de apresentação__: indica em qual bloco (ou conjunto) a pseudopalavra foi
inserida (1, 2, 3 ou 4)
- __Ordem de apresentação__: indica em qual ordem a pseudopalavra foi apresentada
dentro do bloco de apresentação (1 a 93). Para os indivíduos que fizeram toda a 
dinâmica no software, a ordem das pseudopalavras era diferente dentro de cada bloco.

__Problemas de aleatorização__

Para alguns participantes o software Psychopy apresentou problemas e
eles tiveram que continuar o experimento a partir de slides com uma ordem aleatória 
pré-estabelecida. Em outras palavras, todos os indivíduos que em algum momento
acompanharam o experimento pelos slides seguiram com palavras apresentadas na 
mesma ordem (a primeira aleatorização retirada do Excel).

- __Aleatorização__: codifica se o bloco de apresentação foi aleatorizado para o
indivíduo ou  não, e portanto foi considerada a aleatorização prévia (s = o estímulo
foi aleatorizado e n = o estímulo não foi aleatorizado). 




