# Metodologia {#metodologia}

Nessa seção é feita a análise das variáveis linguísticas, extralinguísticas e experimentais com o intuito de caracterizar o processo de acentuação tônica. Para entender quais variáveis de fato têm influência construímos modelos multinomiais mistos com os falantes definidos como efeito aleatório. Assim, além de consider a correlação das respostas do mesmo falante e o desbalanceamento na quantidade de respostas de cada um, essa estrutura possibilita a inclusão de variáveis relacionadas às características dos falantes.

As seguintes variáveis foram consideradas no modelo completo:
- __Variável resposta__: Tonicidade de produção
- __Efeito aleatório__: Efeito de cada falante
_ __Variáveis com efeitos fixos__: Tonicidade alvo, Estrutura da palavra, Grupo de classificação, Segmento modificado, Bloco de apresentação, Aleatorizacao, Música, Línguas, Idade, Gênero, Escolaridade, Área de formação

Com isso, foram construídos modelos considerando o nível Paroxítona como categoria de referência da regressão mutinomial. Ou seja, estaremos comparando através de uma função de ligação logito os níveis Oxítona/Paroxítona e Proparoxítona/Paroxítona. A escolha da categoria Paraxítona como referência aconteceu por ela ser considerada a acentuação tônica mais comum na língua portuguesa. A seguir, apresentamos as formulações matemáticas do modelo no contexto do trabalho

$$ ln[\frac{\pi_{ijOxítona}}{\pi_{ijParoxítona}}] = X'\beta_{(O-Pa)} + b_{i(O-Pa)} $$
com 
 
$i$ = 1,..,34 = Falantes  
$j$ = 1,...,$n_i$ = $j$-ésima pseudopalavra acentuada pelo $i$-ésimo falante  
$X'$ = Matris de variáveis independentes  
$\beta_{(O-Pa)}$ = Vetor de parâmetros  
$b_{i(O-Pa)}$ = Efeito aleatório relacionado ao $i$-ésimo falante

$$ ln[\frac{\pi_{ijProparoxítona}}{\pi_{ijParoxítona}}] = X'\beta_{(Pro-Pa)} + b_{i(Pro-Pa)} $$
com 

$i$ = 1,..,34 = Falantes  
$j$ = 1,...,$n_i$ = $j$-ésima pseudopalavra acentuada pelo $i$-ésimo falante  
$X'$ = Matris de variáveis independentes  
$\beta_{(Pro-Pa)}$ = Vetor de parâmetros  
$b_{i(Pro-Pa)}$ = Efeito aleatório relacionado ao $i$-ésimo falante


Além disso, devido ao experimento relacionado à validação da similaridade/dissimilaridade entre palavra-alvo e pseudopalavra no qual alguma dessas relações não foi de fato validada (Seção 4), testamos se a exclusão de pseudopalavras não validadas afetaria muito o resultado do modelo ajustado à base total. Dessa forma, foi possível entender se essa classificação afetava os valores inferenciais ou se poderímos excluir as observações cuja similaridade/dissimilaridade entre palavra-alvo e pseudopalavra não foi validada.

Retirando amostras aleatórias de apenas 25% de palavras não validadas, observou-se que o resultado do modelo é alterado de formas diferentes, a depender da amostra. 

Como explicado anteriormente, essa variável foi utilizada para validar outra variável da pesquisa (Grupo de classificação). Então, para reduzir a incerteza em relação à definição do Grupo de classificação, decidiu-se por ajustar um modelo apenas com as pseudopalavras validadas e quase validadas, excluindo as não validadas.


## Modelos Ajustados

Consideramos dois modelos possíveis: um com a variável Grupo de classificação, que foi a variável construída pela pesquisadora, e outro em que essa variável é separada em duas: Similaridade e Frequência.

Com esse segundo modelo, podemos identificar o efeito marginal da similaridade ou da frequência de forma separada, o que não é possível fazer com a variável Grupo de classificação, que já considera a interação entre essas duas variáveis. Portanto, o processo de ajuste do modelo e seleção de variáveis foi feito para esses dois modelos, descritos a seguir.

### Modelo com Grupo de classificação

Como o modelo multinomial é constituído de duas regressões neste caso, em que a variável resposta contém três níveis, foi feito um processo de seleção de variáveis _backwards_ manual, considerando o valor-p das estimativas nos dois modelos de forma simultânea.

Adotando 5% como nível de significância, verificou-se que a maior parte das variáveis relacionadas aos falantes  não apresentaram significância nos modelos ajustados. Depois de retirar uma a uma as variáveis não significantes nos dois modelos, testamos retirar a variável extralinguística que apresentou apenas um nível significante (Escolaridade), já que essa variável possuía apenas uma observação em um dos níveis. 

Comparamos o critério de informação de Akaike (AIC) dos modelos com e sem Escolaridade, o modelo sem Escolaridade apresentou menor AIC, logo, concluímos que a exclusão apresentou melhora no modelo.

Portanto, as variáveis que apresentaram significância em pelo menos um nível foram: _tonicidade_alvo_, _estrutura_palavra_, _grupo_, _segmento_modificado_, _bloco_apresentação_ e _aleatorização_. 

As Tabelas A.8 e A.9 contêm as estimativas, erros padrões e valores-p dos efeitos fixos obtidos pelo modelo final ajustado. A Tabela A.8 apresenta os valores para o modelo dos níveis Oxítona/Paroxítona e a Tabela A.9 apresenta os valores para o modelo dos níveis Proparoxítona/Paroxítona. É importante observar que, como as variáveis foram selecionadas de forma simultânea para os dois modelos, nem sempre os coeficientes das variáveis serão representadas em ambos as equações, pois podem ter níveis de significância diferentes entre os modelos Oxítona/Paroxítona e Proparoxítona/Paroxítona.


```{r}
broom::tidy(mf) %>% dplyr::filter(stringr::str_detect(term, "^prop"))
broom::tidy(mf) %>% dplyr::filter(stringr::str_detect(term, "^ox"))
```


## Interpretações dos parâmetros

A partir da saída percebe-se que, mantidas as demais variáveis em seus respectivos níveis de referência:

1) A probabilidade de produção oxítona (ao invés de produção paroxítona)
quando a estrutura da palavra é CV-CV-CVC é, aproximadamente, 73 vezes a probabilidade de produção
oxítona (ao invés de produção paroxítona) quando a estrutura da palavra é CV-CV-CV. Já a 
probabilidade de produção proparoxítona (ao invés de produção paroxítona) quando a estrutura da
palavra é CV-CV-CVC é, aproximadamente, 6 vezes a probabilidade de produção proparoxítona 
(ao invés de produção paroxítona) quando a estrutura da palavra é CV-CV-CV. 

2) A probabilidade de produção oxítona (ao invés de produção paroxítona) quando a palavra-alvo é
paroxítona é, aproximadamente, 0,25 vezes a probabilidade de produção oxítona (ao invés de produção
paroxítona) quando a palavra-alvo é oxítona. Já a probabilidade de produção proparoxítona (ao invés
de produção paroxítona) quando a palavra-alvo é paroxítona é, aproximadamente, 0,54 vezes a
probabilidade de produção proparoxítona (ao invés de produção paroxítona) quando a palavra-alvo é
oxítona. 

3) A probabilidade de produção oxítona (ao invés de produção paroxítona) quando a palavra-alvo é
proparoxítona é, aproximadamente, 0,13 vezes a probabilidade de produção oxítona (ao invés de
produção paroxítona) quando a palavra-alvo é proparoxítona. Já a probabilidade de produção
proparoxítona (ao invés de produção paroxítona) quando a palavra-alvo é proparoxítona é,
aproximadamente, 5 vezes a probabilidade de produção proparoxítona (ao invés de produção paroxítona)
quando a palavra-alvo é proparoxítona. 

4) A probabilidade de produção oxítona (ao invés de produção paroxítona) quando o segmento modificado
foi uma vogal é, aproximadamente, 1,2 vezes a probabilidade de produção oxítona (ao invés de produção
paroxítona) quando o segmento modificado foi uma consoante. Já a probabilidade de produção
proparoxítona (ao invés de produção paroxítona) quando o segmento modificado foi uma vogal é,
aproximadamente, 1,3 vezes a probabilidade de produção proparoxítona (ao invés de produção
paroxítona) quando o segmento modificado foi uma consoante. 

5) A probabilidade de produção oxítona (ao invés de produção paroxítona) quando a pseudopalavra é do
grupo 2 é 0 vezes a probabilidade de produção oxítona(ao invés de produção paroxítona) quando a
pseudopalavra é do grupo 1. Já a probabilidade de produção proparoxítona (ao invés de produção
paroxítona) quando a pseudopalavra é do grupo 2 é 0,26 vezes a probabilidade de produção
proparoxítona(ao invés de produção paroxítona) quando a pseudopalavra é do grupo 1.

A probabilidade de produção oxítona (ao invés de produção paroxítona) quando a pseudopalavra é do
grupo 3 é 1,74 vezes a probabilidade de produção oxítona(ao invés de produção paroxítona) quando a
pseudopalavra é do grupo 1. Já a probabilidade de produção proparoxítona (ao invés de produção
paroxítona) quando a pseudopalavra é do grupo 3 é 0 vezes a probabilidade de produção proparoxítona 
(ao invés de produção paroxítona) quando a pseudopalavra é do grupo 1. 

A probabilidade de produção oxítona (ao invés de produção paroxítona) quando a pseudopalavra é do
grupo 4 é 1,52 vezes a probabilidade de produção oxítona (ao invés de produção paroxítona) quando a
pseudopalavra é do grupo 1. Já a probabilidade de produção proparoxítona (ao invés de produção
paroxítona) quando a pseudopalavra é do grupo 4 é 0,32 vezes a probabilidade de produção
proparoxítona (ao invés de produção paroxítona) quando a pseudopalavra é do grupo 1. 

6) A probabilidade de produção oxítona (ao invés de produção paroxítona) quando é, aproximadamente,
0,14 vezes a probabilidade de produção oxítona (ao invés de produção paroxítona). Já a probabilidade
de produção proparoxítona (ao invés de produção paroxítona)  é, aproximadamente, 0,02 vezes a
probabilidade de produção proparoxítona (ao invés de produção paroxítona). 



### Modelo com Similaridade e Frequência


### Variáveis de interesse

Outro ponto de destaque é a variável Aleatorização que apresentou significância estatística na comparação Oxítona/Paroxítona. Ou seja, há evidências de que o problema de conexão durante o experimento impactou na acentuação tônica das pseudopalavras.


\newpage
