# Conclusão da Descritiva e Próximos Passos


A partir dos resultados presentes nas tabelas da seção anterior, percebe-se um 
comportamento não homogêneo entre níveis de algumas variáveis.Portanto, o próximo
passo do estudo consite e,realizar uma análise univariada, com testes qui-quadrado,
que permite analisar a relação de independência entre variáveis qualitativas. Algumas hipóteses iniciais são:

1. Entender se os grupos experimentais afetam a acentuação das pseudopalavras 

$H_0$: O grupo experimental determina a localização acentual
$H_1$: O grupo experimental não determina a localização acentual

2.Observar se a tonicidade de produção é coincidente com a tonicidade alvo

$H_0$: Há associação entre os padrões acentuais
$H_1$: Não há associação entre os padrões acentuais

3. Entender se a tonicidade da palavra real influencia mais em pseudopalavras 
mais similares e menos em pseudopalavras mais dissimilares

$H_0$: A taxa de similaridade não influencia na associação acentual
$H_1$: A taxa de similaridade influencia na associação acentual

4. A validação da similaridade e dissimilaridade em relação à palavra alvo afeta a acentuação tônica das pseudopalavras?

$H_0$: Pseudopalavras não validadas têm o mesmo comportamento das validadas e quase validadas
$H_1$: Pseudopalavras não validadas têm comportamento distinto das validadas e quase validadas

5. Entender se o conhecimento em Música influencia na acentuação tônica
$H_0$: Não há associação entre conhecimento em Música e a tonicidade produzida
$H_1$: Há associação entre conhecimento em Música e a tonicidade produzida

6. Entender se a estudantes no início da graduação em Letras tem um comportamento
diferente no processo de acentuação tônica
$H_0$: Não há associação entre graduação em Letras e a tonicidade produzida
$H_1$: Há associação entre graduação em Letras e a tonicidade produzida

Além disso, a parte inferencial da análise será pautada em um modelo hierárquico 
no qual os participantes representam um nível com efeito aleatório, e a variável 
dependente será a tonicidade produzida em cada pseudopalavra. 






