# (APPENDIX) Apêndices {-} 
# Tabelas {#tabelas}

```{r perfil-informantes }
pseudopalavras::dados %>% 
  dplyr::distinct(informante, .keep_all = TRUE) %>% 
  dplyr::mutate(naturalidade = dplyr::case_when(
    naturalidade == "São Paulo" ~ "São Paulo, SP",
    stringr::str_detect(naturalidade, "SP") ~ "Outros municípios de SP",
    TRUE ~ "Outras UF"
  )) %>% 
  dplyr::count(naturalidade, sort = TRUE) %>% 
  knitr::kable(
    caption = "Perfil dos participantes de acordo com a Naturalidade.",
    booktabs = TRUE,
    table.attr = "style='width:100%;'",
    col.names = c("Naturalidade", "Total")
  ) %>% 
  kableExtra::kable_styling(full_width = TRUE)
```
<br>
```{r area-formacao}
participantes %>% 
  dplyr::count(area_formacao, sort = TRUE) %>% 
  dplyr::mutate(n = glue::glue("{n} ({scales::percent(n/sum(n))})")) %>% 
  knitr::kable(
    col.names = c("Área de formação", "Total"),
    caption = "Frequência da variável dicotômica Área de formação.",
    booktabs = TRUE,
    table.attr = "style='width:100%;'"
  ) %>% 
  kableExtra::kable_styling(full_width = TRUE)
```
<br>
```{r area-escolaridade}
participantes %>%
  dplyr::mutate(escolaridade = dplyr::case_when(
    escolaridade == "Mestrado" ~ "4. Pós-Graduação (Completo ou Incompleto)",
    escolaridade == "Mestrado Incompleto" ~ "4. Pós-Graduação (Completo ou Incompleto)",
    escolaridade == "Pós-Graduação" ~ "4. Pós-Graduação (Completo ou Incompleto)",
    escolaridade == "Superior Completo" ~ "3. Superior Completo",
    escolaridade == "Superior Incompleto" ~ "2. Superior Incompleto",
    escolaridade == "Fundamental Completo" ~ "1. Fundamental Completo",
  )) %>%
  dplyr::count(escolaridade, area_formacao) %>%
  tidyr::pivot_wider(names_from = area_formacao, values_from = n) %>%
  tidyr::replace_na(list(Letras = 0)) %>%
  dplyr::mutate(Total = Outro + Letras) %>%
  janitor::adorn_totals() %>%
  dplyr::mutate(dplyr::across(
    Outro:Total, ~paste0(.x, " (", scales::percent(.x/34, .1), ")"))) %>% 
  knitr::kable(
    col.names = c("Escolaridade", "Outro", "Letras", "Total"),
    caption = "Escolaridade dos participantes pela área de formação.",
    booktabs = TRUE,
    table.attr = "style='width:100%;'"
  ) %>% 
  kableExtra::kable_styling(full_width = TRUE)

```
<br>
```{r linguas}
participantes %>% 
  dplyr::count(linguas, sort = TRUE) %>% 
  dplyr::mutate(linguas = ifelse(linguas == 1, "Sim", "Não")) %>% 
   knitr::kable(
    col.names = c("Conhecimento em línguas", "Total"),
    caption = "Frequência da variável dicotômica Línguas.",
    booktabs = TRUE,
    table.attr = "style='width:100%;'"
  ) %>% 
  kableExtra::kable_styling(full_width = TRUE)
```
<br>
```{r musica}
participantes %>% 
  dplyr::count(musica, sort = TRUE) %>% 
  dplyr::mutate(musica = ifelse(musica == 1, "Sim", "Não")) %>% 
  knitr::kable(
    col.names = c("Conhecimento em música", "Total"),
    caption = "Frequência da variável dicotômica Música.",
    booktabs = TRUE,
    table.attr = "style='width:100%;'"
  ) %>% 
  kableExtra::kable_styling(full_width = TRUE)
```

<br>
```{r grupo-producao}
pseudopalavras::dados %>% 
  dplyr::count(tonicidade_producao, grupo) %>% 
  tidyr::pivot_wider(names_from = grupo, values_from = n) %>%
  setNames(c(
    "tonicidade_producao", 
    "g1",
    "g2",
    "g3",
    "g4"
  )) %>% 
  dplyr::mutate(total = g1 + g2 + g3 + g4) %>% 
  dplyr::transmute(
    tonicidade_producao,
    g1 = glue::glue("{g1} ({scales::percent(g1/total)})"),
    g2 = glue::glue("{g2} ({scales::percent(g2/total)})"),
    g3 = glue::glue("{g3} ({scales::percent(g3/total)})"),
    g4 = glue::glue("{g4} ({scales::percent(g4/total)})"),
    total = glue::glue("{total} ({scales::percent(total/total)})")
  ) %>% 
  knitr::kable(
    col.names = c(
      "Tonicidade produção", 
      "1 (Similar de alta freq.)",
      "2 (Dissimilar de alta freq.)",
      "3 (Similar de baixa freq.)",
      "4 (Dissimilar de baixa freq.)",
      "Total"
    ),
    caption = "Frequência do Grupo de classificação por Tonicidade de produção (da pseudopalavra).",
    booktabs = TRUE,
    table.attr = "style='width:100%;'"
  ) %>% 
  kableExtra::add_header_above(
    c(" " = 1, "Grupo de classificação" = 4, " " = 1)
  )
```
<br>
```{r tonicidade-pseudoxalvo2}
pseudopalavras::dados %>%
  dplyr::count(tonicidade_producao, tonicidade_alvo) %>% 
  dplyr::mutate(
    tonicidade_alvo = abjutils::rm_accent(tonicidade_alvo)
  ) %>% 
  tidyr::pivot_wider(names_from = tonicidade_alvo, values_from = n) %>% 
  dplyr::mutate(total = oxitona + paroxitona + proparoxitona) %>% 
  janitor::adorn_totals() %>% 
  dplyr::mutate(
    oxitona = glue::glue("{oxitona} ({scales::percent(oxitona/4845, .1)})"),
    paroxitona = glue::glue("{paroxitona} ({scales::percent(paroxitona/4835, .1)})"),
    proparoxitona = glue::glue("{proparoxitona} ({scales::percent(proparoxitona/2831, .1)})"),
    total = glue::glue("{total} ({scales::percent(total/12511, .1)})")
  ) %>% 
  knitr::kable(col.names = c(
      "Tonicidade produção", "oxítona", "paroxítona", "proparoxítona", "Total"
    ),
    caption = "Frequência da tonicidade das palavras-alvo por nível de tonicidade das pseudopalavras.",
    booktabs = TRUE,
    table.attr = "style='width:100%;'"
  ) %>% 
  kableExtra::add_header_above(
    c(" " = 1, "Tonicidade da palavra-alvo" = 3, " " = 1)
  )
```
<br>

```{r estrut-tonicidade-alvo}
pseudopalavras::dados %>%  dplyr::distinct(palavra_alvo, .keep_all = TRUE) %>% 
  dplyr::count(estrutura_palavra, tonicidade_alvo) %>% 
  tidyr::pivot_wider(names_from = estrutura_palavra, values_from = n) %>% 
  setNames(c("tonicidade", "e1", "e2")) %>% 
  dplyr::mutate(
    total = e1 + e2,
    e1 = glue::glue("{e1} ({scales::percent(e1/total)})"),
    e2 = glue::glue("{e2} ({scales::percent(e2/total)})"),
    total = glue::glue("{total} ({scales::percent(total/total)})")
  ) %>% 
  dplyr::relocate(tonicidade, e1, e2, total) %>% 
  knitr::kable(
    col.names = c("Tonicidade palavra-alvo", "CV-CV-CV", "CV-CV-CVC", "Total"),
    booktabs = TRUE,
    table.attr = "style='width:100%;'",
    caption = "Frequência da Tonicidade alvo por Estrutura das palavras."
  ) %>% 
  kableExtra::add_header_above(
    c(" " = 1, "Estrutura da palavra" = 2, " " = 1)
  )
```

<br>

```{r validacao-grupo-tonicidade}
pseudopalavras::dados %>% 
  dplyr::count(grupo, tonicidade_producao, validacao) %>% 
  dplyr::mutate(validacao = dplyr::case_when(
    validacao == "n" ~ "Não Validada",
    validacao == "s" ~ "Validada",
    validacao == "q" ~ "Quase Validada"
  )) %>% 
  tidyr::pivot_wider(names_from = validacao, values_from = n) %>% 
  janitor::adorn_totals() %>% 
  janitor::adorn_percentages(denominator = "col") %>% 
  janitor::adorn_pct_formatting(digits = 1) %>% 
  janitor::adorn_ns(position = "front") %>% 
  knitr::kable(
    col.names = c(
      "Grupo de classificação", "Tonicidade produção", "Não Validada", "Quase Validada", 
      "Validada"
    ),
    caption = "Tonicidade de pseudopalavras por Grupo e Validação.",
    booktabs = TRUE,
    table.attr = "style='width:100%;'"
  ) %>% 
  kableExtra::add_header_above(
    c(" " = 2, "Status Validação" = 3)
  )
```

<br>
```{r gwet-grupo}
teste_grupo <- function(num_grupo) {
  da <- pseudopalavras::dados %>%
    dplyr::filter(grupo == num_grupo) %>%
    dplyr::select(informante, tonicidade_producao, pseudopalavra) %>%
    dplyr::group_by(pseudopalavra) %>%
    dplyr::summarise(
      oxitona = sum(tonicidade_producao == "oxítona"),
      paroxitona = sum(tonicidade_producao == "paroxítona"),
      proparoxitona = sum(tonicidade_producao == "proparoxítona")
    ) %>%
    dplyr::select(-pseudopalavra)
  gwet.ac1.dist(da) %>%
    dplyr::mutate(grupo = paste0("Grupo ", num_grupo)) %>%
    dplyr::relocate(grupo)
}

purrr::map_dfr(1:4, teste_grupo) %>%
  dplyr::select(grupo, coeff) %>%
  knitr::kable(
    col.names=c("Grupo de Classificação","Valor da Estatística"), 
    booktabs = TRUE,
    table.attr = "style='width:100%;'"
  ) %>%
  kableExtra::kable_styling(full_width = TRUE)
```

<br>

```{r gwet-estrutura}
teste_estrutura <- function(estrut) {
  da <- pseudopalavras::dados %>%
    dplyr::filter(estrutura_palavra == estrut) %>%
    dplyr::select(informante, tonicidade_producao, pseudopalavra) %>%
    dplyr::group_by(pseudopalavra) %>%
    dplyr::summarise(
      oxitona = sum(tonicidade_producao == "oxítona"),
      paroxitona = sum(tonicidade_producao == "paroxítona"),
      proparoxitona = sum(tonicidade_producao == "proparoxítona")
    ) %>%
    dplyr::select(-pseudopalavra)
  gwet.ac1.dist(da) %>%
    dplyr::mutate(estrutura = estrut) %>%
    dplyr::relocate(estrutura)
}

purrr::map_dfr(unique(pseudopalavras::dados$estrutura_palavra), teste_estrutura) %>% 
  dplyr::select(estrutura, coeff)%>%
  knitr::kable(
    col.names=c("Estrutura da Palavra","Valor da Estatística"), 
    booktabs = TRUE,
    table.attr = "style='width:100%;'"
  )%>%
  kableExtra::kable_styling(full_width = TRUE)

```

<br>

```{r gwet-segmento}
teste_segmento <- function(seg) {
  da <- pseudopalavras::dados %>%
    dplyr::filter(segmento_modificado == seg) %>%
    dplyr::select(informante, tonicidade_producao, pseudopalavra) %>%
    dplyr::group_by(pseudopalavra) %>%
    dplyr::summarise(
      oxitona = sum(tonicidade_producao == "oxítona"),
      paroxitona = sum(tonicidade_producao == "paroxítona"),
      proparoxitona = sum(tonicidade_producao == "proparoxítona")
    ) %>%
    dplyr::select(-pseudopalavra)
  gwet.ac1.dist(da) %>%
    dplyr::mutate(segmento_modificado = seg) %>%
    dplyr::relocate(segmento_modificado)
}

purrr::map_dfr(
  unique(pseudopalavras::dados$segmento_modificado), 
  teste_segmento
) %>%
  dplyr::select(segmento_modificado, coeff) %>%
  knitr::kable(
    col.names=c("Segmento Modificado", "Valor da Estatística"), 
    booktabs = TRUE,
    table.attr = "style='width:100%;'"
  )%>%
  kableExtra::kable_styling(full_width = TRUE)

```


\newpage


