# Gráficos {#graficos}

```{r idade_genero, fig.cap = "Idade dos participantes distribuída pelo Genêro"}
participantes %>%
  dplyr::mutate(idade_cat = dplyr::case_when(
    idade <= 20 ~ "Entre 18 e 20 anos",
    idade <= 30 ~ "Entre 21 e 30 anos",
    idade <= 38 ~ "Entre 31 e 38 anos",
    TRUE ~ "Entre 38 e 60 anos",
  )) %>%
  dplyr::count(genero, idade_cat) %>%
  dplyr::group_by(idade_cat) %>%
  dplyr::mutate(pct = scales::percent(n/sum(n), .1)) %>% 
  ggplot2::ggplot(ggplot2::aes(y = n, x = idade_cat, fill = genero,
                               label = glue::glue("{n} ({pct})"))) +
  ggplot2::geom_col() +
  ggplot2::geom_text(position = ggplot2::position_stack(vjust = .5)) +
  ggplot2::scale_fill_manual(values=c("turquoise4","orchid4" ))+
  ggplot2::theme_minimal(18) +
  ggplot2::labs(
    x = "Idade",
    y = "N",
    fill = "Gênero"
  ) +
  ggplot2::labs(
    x = "Idade categorizada dos participantes",
    y = "N",
    fill = "Gênero")
```
<br>
```{r area_linguas, fig.cap = "Conhecimento em outras línguas por área de formação"}
 participantes %>%
  dplyr::mutate(linguas = ifelse(linguas == 0, "Não", "Sim")) %>%
  dplyr::count(area_formacao, linguas, sort = TRUE) %>%
  dplyr::group_by(linguas) %>%
  dplyr::mutate(pct = scales::percent(n/sum(n), .1)) %>%
  ggplot2::ggplot(ggplot2::aes(
    x = linguas, y = n, fill = area_formacao,
    label = glue::glue("{n} ({pct})")
  )) +
  ggplot2::geom_col() +
  ggplot2::geom_text(position = ggplot2::position_stack(vjust = .5)) +
  ggplot2::scale_fill_manual(values=c("turquoise4","orchid4" ))+
  ggplot2::theme_minimal(18) +
  ggplot2::labs(
    x = "Conhecimento em outra(s) língua(s)",
    y = "N",
    fill = "Área de formação")
```
<br>

```{r fluxo-1, fig.cap = "Fluxo de tonicidade no Grupo Similar de Alta Frequência"}
pseudopalavras::dados %>%
  dplyr::mutate(Coincidente = tonicidade_producao == tonicidade_alvo) %>%
  dplyr::count(grupo, tonicidade_producao, tonicidade_alvo, Coincidente) %>%
  dplyr::filter(grupo == 1) %>%
  dplyr::mutate(pct = n/sum(n)) %>%
  ggplot2::ggplot(ggplot2::aes(
    axis1 = tonicidade_alvo, axis2 = tonicidade_producao, y = pct
  )) +
  geom_alluvium(ggplot2::aes(fill = tonicidade_alvo)) +
  geom_stratum() +
  ggplot2::geom_text(
    stat = "stratum",
    ggplot2::aes(label = after_stat(stratum))
  ) +
  labs(fill="Tonicidade da palavra-alvo", y="", x="Grupo Similar de Alta Frequência")+
  ggplot2::scale_y_continuous(labels = scales::label_percent()) +
  ggplot2::scale_fill_viridis_d()+
  ggplot2::theme_minimal() +
  theme(plot.background = element_rect(fill = '#fffaf5ff', color = "#fffaf5ff"),
        axis.text.x=element_blank())

```
<br>

```{r fluxo-2, fig.cap = "Fluxo de tonicidade no Grupo Dissimilar de Alta Frequência"}
pseudopalavras::dados %>%
  dplyr::mutate(Coincidente = tonicidade_producao == tonicidade_alvo) %>%
  dplyr::count(grupo, tonicidade_producao, tonicidade_alvo, Coincidente) %>%
  dplyr::filter(grupo == 2) %>%
  dplyr::mutate(pct = n/sum(n)) %>%
  ggplot2::ggplot(ggplot2::aes(
    axis1 = tonicidade_alvo, axis2 = tonicidade_producao, y = pct
  )) +
  geom_alluvium(ggplot2::aes(fill = tonicidade_alvo)) +
  geom_stratum() +
  ggplot2::geom_text(
    stat = "stratum",
    ggplot2::aes(label = after_stat(stratum))
  ) +
  labs(fill="Tonicidade da palavra-alvo", y="", x="Grupo Dissimilar de Alta Frequência")+
  ggplot2::scale_y_continuous(labels = scales::label_percent()) +
  ggplot2::scale_fill_viridis_d()+
  ggplot2::theme_minimal() +
  theme(plot.background = element_rect(fill = '#fffaf5ff', color = "#fffaf5ff"),
        axis.text.x=element_blank())

````

<br>

```{r fluxo-3, fig.cap = "Fluxo de tonicidade no Grupo Similar de Baixa Frequência"}
pseudopalavras::dados %>%
  dplyr::mutate(Coincidente = tonicidade_producao == tonicidade_alvo) %>%
  dplyr::count(grupo, tonicidade_producao, tonicidade_alvo, Coincidente) %>%
  dplyr::filter(grupo == 3) %>%
  dplyr::mutate(pct = n/sum(n)) %>%
  ggplot2::ggplot(ggplot2::aes(
    axis1 = tonicidade_alvo, axis2 = tonicidade_producao, y = pct
  )) +
  geom_alluvium(ggplot2::aes(fill = tonicidade_alvo)) +
  geom_stratum() +
  ggplot2::geom_text(
    stat = "stratum",
    ggplot2::aes(label = after_stat(stratum))
  ) +
  labs(fill="Tonicidade da palavra-alvo", y="", x="Grupo Similar de Baixa Frequência")+
  ggplot2::scale_y_continuous(labels = scales::label_percent()) +
  ggplot2::scale_fill_viridis_d()+
  ggplot2::theme_minimal() +
  theme(plot.background = element_rect(fill = '#fffaf5ff', color = "#fffaf5ff"),
        axis.text.x=element_blank())

```
<br>

```{r fluxo-4, fig.cap = "Fluxo de tonicidade no Grupo Dissimilar de Baixa Frequência"}
pseudopalavras::dados %>%
  dplyr::mutate(Coincidente = tonicidade_producao == tonicidade_alvo) %>%
  dplyr::count(grupo, tonicidade_producao, tonicidade_alvo, Coincidente) %>%
  dplyr::filter(grupo == 4) %>%
  dplyr::mutate(pct = n/sum(n)) %>%
  ggplot2::ggplot(ggplot2::aes(
    axis1 = tonicidade_alvo, axis2 = tonicidade_producao, y = pct
  )) +
  geom_alluvium(ggplot2::aes(fill = tonicidade_alvo)) +
  geom_stratum() +
  ggplot2::geom_text(
    stat = "stratum",
    ggplot2::aes(label = after_stat(stratum))
  ) +
  labs(fill="Tonicidade da palavra-alvo", y="", x="Grupo Dissimilar de Baixa Frequência")+
  ggplot2::scale_y_continuous(labels = scales::label_percent()) +
  ggplot2::scale_fill_viridis_d()+
  ggplot2::theme_minimal() +
  theme(plot.background = element_rect(fill = '#fffaf5ff', color = "#fffaf5ff"),
        axis.text.x=element_blank())
```



