---
title: "CENTRO DE ESTATÍSTICA APLICADA – CEA – USP"
subtitle: "RELATÓRIO DE CONSULTA"
author: 
  - Giovanna Vilar
  - Mariana Almeida
  - Renata Hirota
date: "`r format(Sys.Date(), '%B/%Y')`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


__TÍTULO:__ Fatores associados à evasão e conclusão de curso na UFRJ: análise de heterogeneidade

__PESQUISADOR:__ Melina Klitzke Martins

__ORIENTADOR:__ Rosana Heringer, Flávio Carvalhaes

__INSTITUIÇÃO:__ Universidade Federal do Rio de Janeiro

__FINALIDADE DO PROJETO:__ Doutorado

__PARTICIPANTES DA ENTREVISTA:__ 

- Melina Klitzke Martins
- Flávio Carvalhaes
- Monica Carneiro Sandoval 
- Denise Aparecida Botter
- Viviana Giampaoli
- Giovanna Vilar
- Mariana Almeida
- Renata Hirota

__DATA:__ 23/04/2020

__FINALIDADE DA CONSULTA:__ Consultoria sobre o modelo logístico multinível; auxílio na pós-estimação do modelo e na interpretação dos coeficientes 


__RELATÓRIO ELABORADO POR:__ 
- Giovanna Vilar
- Mariana Almeida
- Renata Hirota

\newpage

# Introdução

A evasão dos alunos no ensino superior é uma situação recorrente e estudada por diversos autores no campo da educação e das ciências sociais.Em suma, como as variações  nos ambientes acadêmicos moldam as experiências e os resultados dos alunos de diferentes  maneiras, as disparidades entre as distribuições dos estudantes em todas as áreas de estudo, ainda  que pequenas, podem contribuir para entender as desigualdades de resultados quanto à evasão de curso.
Logo, o projeto busca analisar quais os fatores estão associados à evasão e conclusão de curso na UFRJ e como o efeito  desses fatores variam entre cursos.
Para isso, será utilizado um modelo logístico multinivel (hierárquico),em que o nível 1 são os estudantes e o nível 2 são  os cursos. 
A pesquisadora busca com a entrevista uma consultoria sobre o modelo logístico multinível e um auxílio na pós-estimação do modelo e na interpretação dos coeficientes.


- Descrição geral do projeto, incluindo a utilidade prática. 
- Indicação do tipo de estudo: experimento laboratorial, estudo observacional,
ensaio clínico, etc. 
- Finalidade da entrevista: planejamento amostral, elaboração de questionário,
crítica de análises realizadas, sugestão para análise, etc.

# Descrição do estudo

O estudo foi planejado como um modelo logístico multinivel (hierárquico),em que o nível 1 são os estudantes e o nível 2 são os cursos. A pesquisadora selecionou todos os cursos de modalidade presencial ofertados pela UFRJ e, a partir da volumetria, agrupou-os de acordo com o tipo de curso. Por exemplo, cursos como Letras-Espanhol, Letras-Inglês e Letras-Português foram agrupados no mesmo bloco. Ao fim desse agrupamento, foram obtidos 45 clusters. É importante destacar que o curso de medicina foi excluído da análise pois não era possível acompanhar esses ingressantes. Além disso, cada cluster possui um minímo de 30 observações.
As unidades amostrais da pesquisa são os ingressantes no primeiro semestre do ano de 2014, um total de 4.480 observações. Todos esses alunos foram seguidos pelo número de matrícula até um ano e meio após o primeiro semestre de 2019. 
Essa é uma pesquisa longitudinal mas, como informado pela pesquisadora, no modelo sugerido nesse relatório não será considerado esse planejamento

- Tipo de planejamento/amostragem (número de fatores, níveis, presença de dados incompletos, etc.). 
- Identificação e número de unidades amostrais. 

# Descrição das Variáveis e Processo de Coleta de Dados

A base de dados utilizada foi construída a partir dos microdados da coorte fornecidos pela Divisão de Registro de Estudante (DRE/ Pr1) da UFRJ. A maioria das informações são coletadas através do questionário socioeconômico, produzido e aplicado pela instituição no ato da pré-matrícula do estudante. O bom índice de  respostas, possivelmente, deve-se ao fato de que o estudante precisa apresentar o comprovante  da realização da pré-matrícula, exigido no ato de confirmação da matrícula presencial. O referido  questionário é composto por questões que abordam, entre outras informações, aspectos  socioeconômicos, culturais, escolares, de composição familiar e de escolha e expectativas sobre o  curso e sobre a instituição.
A variável dependente (resposta) utilizada nessa análise éa evasão do curso no primeiro ano  (1° e 2° semestre), representada por 0 e 1 (0= não evadiu; 1= evadiu). O conceito de evasão aqui utilizado é o de evasão do  curso, que é aquela em que o aluno deixa o curso de origem por qualquer razão (LOBO, 2012). Essas variáveis foram construídas através da combinação da variável de tempo que o indivíduo  permaneceu no curso e a situação de matrícula em cada semestre – ativa, trancada, cancelada,  cancelado por conclusão de curso. Destacamos que apenas aqueles que tiveram suas matrículas no curso canceladas (exceto o cancelamento por conclusão de curso), é que foram considerados  evadidos.  
Em um estudo multinivel as variáveis independentes são classificados em dois tipos: variáveis de nível 1 variáveis de nível 2. Aqui, as variáveis de nível 1 são as de origem dos estudantes:  
  
- Cor/Raça (0 = brancos e 1 = pretos e  pardos)  
- Sexo (0 = feminino e 1 = masculino)  
- Status socioeconômico da família (SES), mensurado pela maior escolaridade do pai ou da mãe (0 = menos que o ensino superior e 1= ensino superior)  
- Nota no ENEM no ano de entrada    
- Variável que diz respeito a questão “se foi a primeira opção de curso”  
(0 = sim; 1 = não)  
- Variável que diz respeito a questão “se a nota de corte influenciou na escolha do curso” (0 = não; 1= sim)  
- Coeficiente de Rendimento acumulado por semestre (CRa), relacionado ao último semestre acompanhado  
  
No nível do curso, inicialmente a pesquisadora criou uma variável de seletividade de curso  utilizando a nota mediana do curso no Enem. Se a nota mediana do curso no Enem era maior que  a nota mediana no Enem de toda UFRJ, o curso é mais seletivo, se a nota  mediana do curso no Enem era menor que a nota mediana no Enem da UFRJ, o curso é menos  seletivo   
  
- Seletividade (menos seletivo = 0 e mais seletivo=1)
  
Os dados originais estão armazenados em Excel e o modelo foi construído no software Stata

- Denominação e classificação das variáveis. 
- Codificação. 
- Tipo de questionários ou formulários. 
- Forma de armazenagem de dados. 
- Recursos computacionais disponíveis. 

# Situação do Projeto 

O projeto encontra-se na fase de testes dos modelos multiníveis. Após a entrevista com a pesquisadora algumas críticas à análise feita foram apontadas. Primeiramente, variáveis de nível 1 que podem ser estaticamente significantes foram excluídas do modelo testado. Anteriormente, um modelo de sobrevivência foi construído e seus resultados utilizados para determinar as variáveis a serem utilizadas nessa fase do estudo.Salientamos que essa não é uma tomada de decisão correta pois variáveis que não se mostraram significante na primeira etapa podem ser importantes na determinação do modelo multinível. São momentos e modelos diferentes, logo, todas as variáveis que a pesquisadora acredita que afeta a evasão do curso devem ser testadas.
Além disso, as variáveis contínuas nota do ENEM e CRa possuem magnetudes muito distintas. O CRa é uma noite que varia de 0 à 10 enquanto as notas do ENEM estão em uma escala de 0 à 1000. Essa diferença entre as escalas pode desencadear erros de convergência durante os testes no software.
Outro problema à análise realizada é a forma como as saídas do stata estão sendo apresentadas e analisadas

- Fase atual de implementação. 
- Descrição e críticas às análises já realizadas. 
- Recursos disponíveis. 
- Limitações de custo e tempo. 
- Problemas relacionados à coleta de dados. 

# Conclusão e respostas as perguntas da pesquisadora

## 1.1 Comentários sobre aspectos gerais do projeto
  

## 1.2 Sugestões sobre as variáveis

A primeira sugetão que oferecemos é incluir no modelo todas as variáveis com bom preenchimento (sem muitos MISSING) que a pesquisadora acredita que podem ter algum efeito na evasão do curso. Durante os testes dos modelos algumas vão mostrar-se significantes e outras não, porém, é importante testá-las. Além disso, também sugerimos o acrescimo de variáveis no nível 2. Por exemplo, o comportamento de evasão dos alunos parece ser diferente entre as áreas do conhecimento (Humanas, Exatas e Biológicas), logo, seria interessante construir essa variável categórica de curso.  
A seguir, incluímos uma lista de variáveis a ser incluídas no estudo:  
  
- Renda Familiar, Nível 1  
- Área do conhecimento do curso, Nível 2 (Humanas, Exatas e Biológicas)  
- Média da nota do ENEM do curso, Nível 2  
- Média do CRa do curso, Nível 2  
  
Por fim, destacamos a importância de padronizar as variáveis contínuas referentes à nota do ENEM, pois, como explicado anteriormente, as magnetudes distintas entre CRa e esse valor podem interferir na convergência matemática. A sugestão nesse relatório é tranformar os valores da variável de nota em números na escala de 0 à 10, a mesma utilizada no coeficiente de Rendimento acumulado por semestre

## 1.3 Como construir o modelo?

Passo 1: Ajuste do modelo sem variáveis independentes (modelo nulo) para calcular o coeficiente de correlação intraclasse e testar se as
variâncias em diferentes cursos são homogêneas
  
Passo 2: Incluir as variáveis independentes uma de cada vez e verificar a significância e o BIC de cada modelo; sendo o modelo escolhido nesse primeiro passo o que apresentar o coeficiente significativo e o menor BIC (pode ser o AKAIKE?)
  
Passo 3: Acrescentar novas variáveis até que nenhuma outra seja significativa,
chegando a um ou vários candidatos a modelo final
  
Passo 4: Fazer o diagnóstico dos candidatos a modelo final, verificando os
pressupostos e a qualidade do ajuste
  
  Fonte: https://bdm.unb.br/bitstream/10483/10032/1/2014_AlexLuizMartinsMatheusdaRocha.pdf
  
## 1.4 Como interpretar o modelo?

## 1.5 Exemplo de análise a partir da saída do software Stata

## 1.6 Sugestões de como avaliar a qualidade do ajuste do modelo logistíco multinivel

Quando construímos um modelo é sempre necessário checar a eficácia do mesmo. Além disso, precisa-se utilizar uma métrica para comparar diferentes modelos e encontrar qual o melhor para o conjunto de dados. Assim, esse tópico foca em apresentar medidas de desempenho para o ajuste da regressão logística multinível.

Acurácia e Sensibilidade
QQplot resíduos
Máxima Verossimilhança


## 1.4 Bibliografia

- Comentários sobre aspectos gerais do projeto: viabilidade, abrangência das 
conclusões, etc. 
- Considerações sobre a condução do projeto: desvios em relação ao objetivo.
- Sugestões para análise estatística: modelos, técnicas apropriadas, etc.
- Bibliografia apropriada para o pesquisador. 
- Possibilidade de execução através do CEA ou outras alternativas.
